Repository cardstack/cardstack, pull requests merged in 2022-12, with the labels that each got.

#3457 Begin acceptance test for scheduling a one-time payment
  packages/boxel/addon/components/boxel/input/selectable-token-item/index.gts
  packages/boxel/addon/components/boxel/toggle-button-group/index.gts
  packages/cardpay-sdk/sdk/network-config-utils.ts
  packages/safe-tools-client/app/components/schedule-payment-form-action-card/index.gts
  packages/safe-tools-client/app/components/schedule-payment-form-action-card/ui/index.css
  packages/safe-tools-client/app/components/schedule-payment-form-action-card/ui/index.gts
  packages/safe-tools-client/app/components/schedule-payment-form-action-card/validator.ts
  packages/safe-tools-client/app/services/tokens.ts
  packages/safe-tools-client/app/utils/owner.ts
  packages/safe-tools-client/package.json
  packages/safe-tools-client/tests/acceptance/scheduling-test.ts
  packages/safe-tools-client/tests/integration/schedule-payment-form-action-card-test.ts
  packages/safe-tools-client/tests/support/tokens.ts
  packages/safe-tools-client/tests/support/ui-test-helpers.ts
  packages/safe-tools-client/tests/unit/components/schedule-payment-form-action-card/validator-test.ts
  packages/safe-tools-client/types/ember-power-select/test-support/index.d.ts
Labels: enhancement

#3470 Field-level error states for scheduled payment form
  packages/boxel/addon/components/boxel/input-group/accessories/index.gts
  packages/boxel/addon/components/boxel/input-group/index.css
  packages/boxel/addon/components/boxel/input-group/index.gts
  packages/boxel/addon/components/boxel/input/error-message/index.css
  packages/boxel/addon/components/boxel/input/error-message/index.gts
  packages/boxel/addon/components/boxel/input/index.css
  packages/boxel/addon/components/boxel/input/index.gts
  packages/boxel/addon/components/boxel/input/selectable-token-amount/index.gts
  packages/boxel/addon/components/boxel/input/token-select/index.css
  packages/boxel/addon/components/boxel/input/token-select/index.gts
  packages/boxel/addon/components/boxel/radio-input/index.gts
  packages/boxel/addon/components/boxel/radio-input/item/index.css
  packages/boxel/addon/components/boxel/radio-input/item/index.gts
  packages/boxel/addon/components/boxel/select/index.gts
  packages/boxel/addon/components/boxel/toggle-button-group/index.css
  packages/boxel/addon/components/boxel/toggle-button-group/index.gts
  packages/safe-tools-client/app/components/schedule-payment-form-action-card/index.gts
  packages/safe-tools-client/app/components/schedule-payment-form-action-card/ui/index.gts
  packages/safe-tools-client/app/components/schedule-payment-form-action-card/validator.ts
  packages/safe-tools-client/tests/unit/components/schedule-payment-form-action-card/validator-test.ts
Labels: enhancement, web

#3475 [Fix]: Update coingeckoId for polygon networks
  packages/cardpay-sdk/sdk/constants.ts
Labels: bug, sdk

#3472 hub: Fix timezone issues in calculating next pay at by making sure all logic is in UTC
  packages/hub/node-tests/utils/scheduled-payments-test.ts
  packages/hub/utils/scheduled-payments.ts
Labels: hub

#3483 Fix deposit modal display of safe info
  packages/safe-tools-client/app/templates/schedule.hbs
Labels: bug

#3487 Make Glint apply to safe-tools-client hbs templates
  packages/boxel/addon/components/boxel/control-panel/index.gts
  packages/boxel/addon/glint.d.ts
  packages/ember-shared/addon/src/glint.ts
  packages/ember-shared/addon/src/helpers/truncate-middle.ts
  packages/safe-tools-client/app/components/connect-button/index.gts
  packages/safe-tools-client/app/components/deposit-modal/index.gts
  packages/safe-tools-client/app/components/network-connect-modal/index.gts
  packages/safe-tools-client/app/components/safe-info/index.gts
  packages/safe-tools-client/app/components/schedule-collapse-panel/index.gts
  packages/safe-tools-client/app/controllers/application.ts
  packages/safe-tools-client/app/services/network.ts
  packages/safe-tools-client/app/templates/application.hbs
  packages/safe-tools-client/app/templates/schedule.hbs
  packages/safe-tools-client/types/global.d.ts
Labels: internal

#3494 Add missing contract addresses
  packages/cardpay-cli/utils.ts
  packages/cardpay-sdk/contracts/addresses.ts
  packages/cardpay-sdk/sdk/constants.ts
Labels: sdk

#3500 hub: Change Docker setup for Prisma
  packages/hub/Dockerfile
  packages/hub/package.json
  yarn.lock
Labels: bug, hub, dependencies

#3497 Add table: reward root index
  packages/hub/config/structure.sql
  packages/hub/db/migrations/20221215102320386_reward-root-index.ts
  packages/hub/prisma/schema.prisma
Labels: hub, rewards

#3505 Use ethers provider instead of web3.js
  packages/cardpay-sdk/index.ts
  packages/cardpay-sdk/sdk/assets.ts
  packages/cardpay-sdk/sdk/version-resolver.ts
  packages/safe-tools-client/app/services/safes.ts
  packages/safe-tools-client/app/services/scheduled-payments-sdk.ts
  packages/safe-tools-client/app/services/wallet.ts
  packages/safe-tools-client/app/utils/chain-connection-manager.ts
Labels: safe-tools

#3469 Gas range option fetching, calculations and display
  packages/boxel/addon/components/boxel/toggle-button-group/index.css
  packages/cardpay-sdk/index.ts
  packages/cardpay-sdk/sdk/utils/general-utils.ts
  packages/safe-tools-client/app/components/schedule-payment-form-action-card/index.gts
  packages/safe-tools-client/app/components/schedule-payment-form-action-card/ui/index.gts
  packages/safe-tools-client/app/components/schedule-payment-form-action-card/validator.ts
  packages/safe-tools-client/app/services/scheduled-payments-sdk.ts
  packages/safe-tools-client/tests/index.html
  packages/ssr-web/app/utils/web3-strategies/types.ts
  packages/web-client/app/utils/token.ts
  packages/web-client/app/utils/web3-strategies/layer2-chain.ts
  packages/web-client/app/utils/web3-strategies/types.ts
Labels: enhancement

#3506 Polyfill atob in ssr-web fastboot
  packages/ssr-web/config/fastboot.js
  packages/ssr-web/deployment/fastboot-server.js
Labels: bug

#3507 browserlist update
  yarn.lock
Labels: internal
